### ISSUE TITLE
Review January/2021 FFG mutation in the rules

### ISSUE THREAD

**Issue by romanogit** [keyteki/keyteki#2182]
https://www.fantasyflightgames.com/en/news/2021/1/7/a-mutation-in-the-rules/

- [x] To clarify how The Archivist (Mass Mutation, 113) works with various different card effects, we made the distinction between effects that “put a card into your archives” versus effects that specifically “archive.” This is similar to the distinction between effects that let you “play” cards versus effects that let you “put a card into play.”
- [x] if an upgrade is ever attached to a non-creature card, that upgrade is discarded. (Animator, for example) (#2385)
- [x] we have given Keyforgery a small errata, so it now reads, “When your opponent would forge a key on their turn…” This should avoid the Keyfrog issue without changing the way that Keyforgery actually works in the vast majority of cases. (#2222)
- [x] The “you may” and “if you do” added to Custom Virus will now give players the option to destroy Custom Virus without purging a creature from their hand if they wish, even though we expect this option to be used only in very rare cases.
- [x]  We have reversed our decision, and now we are saying that you can reap with an enraged creature when you play Ghosthawk next to it, because you are not able to fight with it via Ghosthawk’s ability (#2192)
