### ISSUE TITLE
WoE - Saurian house - Specific issues created for pending cards

### ISSUE THREAD

**Issue by romanogit** [keyteki/keyteki#2905]
This list is still based on Spoilers, so, implement with care:
- [x] (231) **Aedile Tullia**: Each time you exalt a friendly non-token creature, make a token creature.
- [x] (233) **Aristotlmimus**: After Reap: If Aristotlmimus has a wisom counter, draw 1 card, archive 1 card, and play a card from your archives. Otherwise, you may play a card from your archives.
- [x] (235) **Conscription**: Play: If there are more enemy creatures than friendly creatures, make a number of token creatures equal to the difference.
- [x] (237) **Edict of Nerotaurus**: After a creature reaps, the next creature used this turn cannot reap. After a creature fights, the next creature used this turn cannot fight.
- [x] (238) **Election**: Each creature gains, "After Reap: Put a `for&#039; or &#039;against&#039; counter on Election".  If there are 6 &#039;for&#039; counters on Election, destroy Election and each creature.  If there are 6 &#039;against&#039; counters on Election, destroy each artifact.
- [x] #3139
- [x] (246) **Platopelta**: After Reap: If Platopelta has a wisdom counter, draw 1 card, archive 1 card, and you may put a wisdom counter on Aristotlmimus. Otherwise, archive 1 card.
- [x] (247) **Rampaging Brutodon**: Play: Make a token creature.
In order to use Rampaging Brutodon, you must destroy a friendly creature.
- [x] (250) **Socraterosaurus**: After Reap: Draw 1 card. You may put a wisdom counter on Platopelta.
- [x] (252) **Tectonic Shift**: Play: Divide each player`s battleline in half as evenly as possible without changing the order of creatures. For each battleline, destroy each creature in one of the halves.
- [x] (253) **Training Costs**: You cannot choose to discard Training Costs from your hand. Play: Lose 2 Aember. If you do not, shuffle Training Costs into your deck.
- [x] (254) **Æmbrosia Outpost**: Action: Put a friendly creature on the bottom of its owner`s deck. If you do,  move 1 Aember from a friendly creature 
to your pool.
- [x] (256) **Chaosodon**: Splash attack 3. (When this creature attacks, also deal 3 Damage to each of the attacked creature`s neighbors.) Before Fight: Deal 3 Damage to each of Chaosodon&#039;s neighbors.
- [x] (259) **Hoplite&#039;s Dory**: This creature gets +2 power for each exhausted creature to its left.
- [x] (260) **Imperator Drusilla**: Play: Destroy another friendly creature.  While there are more enemy creatures than friendly creatures, Imperator Drusilla gains splash-attack 4.
- [x] (261) **Inspiring Oration**: Play: Exalt a friendly creature. Make a token creature for each Aember on that creature.
- [x] (264) **Pax Sauriana**: Play: Ward each creature.
- [x] (265) **Phalanx Leader**: Play: Make a token creature immediately to Phalanx Leader`s left. After Fight/After Reap: Each creature to Phalanx Leader&#039;s left gets +2 power for the remainder of the turn.
- [x] (269) **Aquilia, Lone Hero**: `&#039;Omni:&#039;&#039;&#039; Capture 1 Aember if there are more enemy creatures than friendly creatures.
- [x] (270) **Arm the Plebeians**: Play: Make a token creature. Ward it.
- [x] (271) **Ballistego**: `&#039;Play:&#039;&#039;&#039; You may exalt Ballistego. While Ballistego has Aember on it, it gains splash-attack 3. (When 
this creature attacks, also deal 3 Damage to each of the attacked creature&#039;s neighbors.)
- [x] (273) **Chancellor Dexterus**: After Reap: You may exalt Chancellor Dexterus`s right neighbor. If you do, that creature belongs to house Saurian for the remainder of the turn (instead of its other houses).
- [x] (275) **Epic Poem**: Play: Exalt a friendly creature. Gain 1 Aember for each Aember on that creature.
- [x] (277) **Grammaticus Thrax**: Enhance Capture Capture Damage. (These icons have already been added to cards in your deck.)
- [x] (278) **Legionary Trainer**: Play: Make a token creature. Each friendly token creature enters play ready.
- [x] #3140
- [x] (280) **Pale Into Insignificance**: Play: Destroy each creature with the lowest power.
- [x] (282) **Praetor Marius**: After Reap: For each exhausted creature to Praetor Marius`s left, capture 1 Aember.
- [x] (283) **Recruit**: Play: Make a token creature. If you exalted a friendly creature this turn, archive Recruit.
- [x] (284) **Symposium**: Play: Exalt, ready, and use a friendly creature. If it is a token creature, you may exalt, ready and use another friendly creature.
- [x] (286) **Bellatoran Warrior**: no text
- [x] (287) **Scholar**: After Reap: Draw 1 card.
- [x] #3217
- [x] (289) **Trooper**: After Fight/After Reap: Exalt Trooper.
House saurian - 34 cards

**Comment by romanogit** [comment]
I guess saurian are done
