### ISSUE TITLE
Add AoA Cards - Mars

### ISSUE THREAD

**Issue by Achocholacek** [keyteki/keyteki#6]
- [x] #180 - Exterminate! Exterminate!
- [x] #195 - Entropic Manipulator     
- [x] #210 - Yzphyz Knowdrone     
.
.
.
- [x] #160 - Agent Hoo-man            
- [x] #161 - Carpet Phloxem  
- [x] #162 - Collector Worm         
- [x] #163 - Glyxl Proliferator       
- [x] #164 - Ixxyxli Fixfinger        
- [x] #165 - Mars First
- [x] #166 - Mars Needs Aember                       
- [x] #168 - Mindworm                 
- [x] #170 - Skybooster Squadron
- [x] #171 - Tyxl Beambuckler         
- [x] #173 - Xanthyx Harvester            
- [x] #175 - Zysysyx Shockworm   
- [x] #176 - Aember Conduction Unit   
- [x] #178 - Containment Field        -- Sort of
- [x] #179 - Destroy Them All!        
- [x] #181 - Hypnobeam                
- [x] #184 - Nyzyk Resonator          
- [x] #186 - Phloxem Spike            
- [x] #189 - Storm Crawler
- [x] #194 - Destructive Analysis   
- [x] #196 - Extinction                     
- [x] #201 - Killzord mk. 9001        
- [x] #202 - Martian Generosity
- [x] #205 - Shard of Hate  
- [x] #209 - Yxlyx Stimrager

**Comment by issa** [comment]
#205 - Shard of Hate is done

**Comment by issa** [comment]
Collector Worm is a PR
