### ISSUE TITLE
Add AoA Cards - Sanctum

### ISSUE THREAD

**Issue by Achocholacek** [keyteki/keyteki#7]
- [x] #224 - Smite                 

- [x] #248 - Anahita the Trader    
.
.
.
- [x] #211 - "Lion" Bautrem        
- [x] #212 - Abond the Armorsmith  - sort of but not really
- [x] #213 - Aubade the Grim
- [x] #215 - Bordan the Redeemed   
- [x] #217 - Golden Aura           
- [x] #218 - Hallowed Shield       
- [x] #219 - Healing Blast 
- [x] #220 - Maruck the Marked             
- [x] #223 - Sir Marrows           
- [x] #226 - The Grey Rider        
- [x] #227 - Baron Mengevin        
- [x] #228 - Barrister Joya        
- [x] #229 - Brobnar Ambassador    
- [x] #230 - Dis Ambassador
- [x] #232 - Equalize                    
- [x] #233 - Free Markets          
- [x] #236 - Haedroth's Wall       
- [x] #237 - Logos Ambassador      
- [x] #238 - Mars Ambassador       
- [x] #240 - Prince Derric, Unifier
- [x] #243 - Shadows Ambassador    
- [x] #247 - Untamed Ambassador    
- [x] #253 - Eye of Judgment       
- [x] #255 - Martyr's End          
- [x] #257 - Mother Northelle      
- [x] #260 - Opal Knight
- [x] #261 - Proclamation 346E           
- [x] #263 - Seraphic Armor        
- [x] #264 - Shard of Hope

**Comment by Achocholacek** [comment]
I've tackled the ones I think my brain can comprehend.
Maruck The Marked
Smite
Equalize
Anahita the Trader
and Proclamation 346E are all above my pay grade, or I'm missing something obvious.
